[package]
name = "rustified"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf     = "0.4.0"
exe     = "0.5.5"
walkdir = "2.3.2"
